Enhanced the ui of mobile screen
bsoc-bitbyte/resource-sharing pull request #65
Opened 2023-07-07 11:05 UTC by abansal15

## Overview

1. This PR fixes or fixes part of #55 
2. This PR does the following: [Explain here what your PR does and why]

## Essential Checklist

- [ ] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [ ] "Allow edits from maintainers" is checked. (See [here](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork) for instructions on how to enable it.)
- [ ] The PR is made from a branch that's **not** called "main/master".

## Proof that changes are correct

## PR Pointers

- If you need a review or an answer to a question, and don't have permissions to assign people, **leave a comment** like the following: "{{Question/comment}} @{{reviewer_username}} PTAL".
- Never force push. If you do, your PR will be closed.

2023-07-07 19:56 UTC, sambhavgupta0705 commented
Please check all the tasks and the issue linked to this PR

2023-07-08 05:03 UTC, abansal15 commented
@sambhavgupta0705 i dont understand what i have to do is you are telling to tick the essential checklist items i have done it or anything else ?

2023-07-08 05:07 UTC, sambhavgupta0705 commented
![Screenshot_2023-07-08-10-37-02-35_320a9a695de7cdce83ed5281148d6f19.jpg](https://github.com/bsoc-bitbyte/resource-sharing/assets/81870866/9f112964-1dd0-4bd1-9115-b478f55bb2a9)

I am talking about this

2023-07-08 08:54 UTC, abansal15 commented
@sambhavgupta0705 i have done it

2023-07-08 10:11 UTC, abansal15 commented
![image](https://github.com/bsoc-bitbyte/resource-sharing/assets/120590200/fed710f8-8055-44d9-9f75-d8f9955d7eae)

2023-07-08 10:35 UTC, sambhavgupta0705 requested changes

2023-07-08 10:35 UTC, sambhavgupta0705 commented on src/components/HeroSection/index.jsx
> +        <img src={"https://images.pexels.com/photos/6077089/pexels-photo-6077089.jpeg"} alt={"blueBlob"} className="mobile-sm:!scale-[1.5] hero-section-sm:block hidden absolute mobile:scale-[1.25] w-
change the `alt`

2023-07-08 10:35 UTC, sambhavgupta0705 commented on tailwind.config.js
> +          max: '470px',
Don't change this it will affect other components also

2023-07-09 04:23 UTC, abansal15 commented
@sambhavgupta0705 Done the required changes please review it..

2023-07-09 14:49 UTC, sambhavgupta0705 approved these changes

2023-07-09 14:50 UTC, merged